package sap_api_input_reader

type EC_MC struct {
	ConnectionKey    string `json:"connection_key"`
	Result           bool   `json:"result"`
	RedisKey         string `json:"redis_key"`
	Filepath         string `json:"filepath"`
	Candidate struct {
		Candidate                string `json:"candidate_id"`
		ShipToParty              string `json:"deliver_to"`
		OriginalDeliveryQuantity string `json:"quantity"`
		ActualDeliveryQuantity   string `json:"picked_quantity"`
		Price                    string `json:"price"`
		Batch                    string `json:"batch"`
	} `json:"document"`
	ProductionOrder struct {
		DocumentNo           string `json:"document_no"`
		Status               string `json:"status"`
		DeliverTo            string `json:"deliver_to"`
		Quantity             string `json:"quantity"`
		CompletedQuantity    string `json:"completed_quantity"`
		PlannedStartDate     string `json:"planned_start_date"`
		PlannedValidatedDate string `json:"planned_validated_date"`
		ActualStartDate      string `json:"actual_start_date"`
		ActualValidatedDate  string `json:"actual_validated_date"`
		Batch                string `json:"batch"`
		Work                 struct {
			WorkNo                   string `json:"work_no"`
			Quantity                 string `json:"quantity"`
			CompletedQuantity        string `json:"completed_quantity"`
			ErroredQuantity          string `json:"errored_quantity"`
			Component                string `json:"component"`
			PlannedComponentQuantity string `json:"planned_component_quantity"`
			PlannedStartDate         string `json:"planned_start_date"`
			PlannedStartTime         string `json:"planned_start_time"`
			PlannedValidatedDate     string `json:"planned_validated_date"`
			PlannedValidatedTime     string `json:"planned_validated_time"`
			ActualStartDate          string `json:"actual_start_date"`
			ActualStartTime          string `json:"actual_start_time"`
			ActualValidatedDate      string `json:"actual_validated_date"`
			ActualValidatedTime      string `json:"actual_validated_time"`
		} `json:"work"`
	} `json:"production_order"`
	APISchema               string `json:"api_schema"`
	MaterialCode            string `json:"material_code"`
	ShippingPoint           string `json:"plant/supplier"`
	Stock                   string `json:"stock"`
	DeliveryDocumentType    string `json:"document_type"`
	DeliveryDocument        string `json:"document_no"`
	PlannedGoodsIssueDate   string `json:"planned_date"`
	ActualGoodsMovementDate string `json:"validated_date"`
	Deleted                 bool   `json:"deleted"`
}

type SDC struct {
	ConnectionKey string `json:"connection_key"`
	Result        bool   `json:"result"`
	RedisKey      string `json:"redis_key"`
	Filepath      string `json:"filepath"`
	Candidate     struct {
		CandidateID             string      `json:"CandidateID"`
		Country                 string      `json:"Country"`
		PartnerMemberID         string      `json:"PartnerMemberID"`
		LastLoginDateTime       string      `json:"LastLoginDateTime"`
		LastModifiedDateTime    string      `json:"LastModifiedDateTime"`
		AnonymizedDateTime      string      `json:"AnonymizedDateTime"`
		Anonymized              string      `json:"Anonymized"`
		PublicIntranet          bool        `json:"PublicIntranet"`
		UsersSysID              string      `json:"UsersSysID"`
		ExternalCandidate       bool        `json:"ExternalCandidate"`
		PrimaryEmail            string      `json:"PrimaryEmail"`
		CreationDateTime        string      `json:"CreationDateTime"`
		Zip                     string      `json:"Zip"`
		HomePhone               string      `json:"HomePhone"`
		FirstName               string      `json:"FirstName"`
		PrivacyAcceptDateTime   string      `json:"PrivacyAcceptDateTime"`
		CurrentTitle            string      `json:"CurrentTitle"`
		ConsentToMarketing      string      `json:"ConsentToMarketing"`
		AgreeToPrivacyStatement string      `json:"AgreeToPrivacyStatement"`
		DateofAvailability      string      `json:"DateofAvailability"`
		LastName                string      `json:"LastName"`
		City                    string      `json:"City"`
		DataPrivacyID           string      `json:"DataPrivacyID"`
		VisibilityOption        bool        `json:"VisibilityOption"`
		Address                 string      `json:"Address"`
		CandidateLocale         string      `json:"CandidateLocale"`
		Address2                string      `json:"Address2"`
		ContactEmail            string      `json:"ContactEmail"`
		ShareProfile            string      `json:"ShareProfile"`
		PartnerSource           string      `json:"PartnerSource"`
		MiddleName              string      `json:"MiddleName"`
		CellPhone               string      `json:"CellPhone"`
		Languages               struct {
			BackgroundElementID  string `json:"BackgroundElementID"`
			LastModifiedDateTime string `json:"LastModifiedDateTime"`
			WritingProf          string `json:"WritingProf"`
			Language             string `json:"Language"`
			ReadingProf          string `json:"ReadingProf"`
			BgOrderPos           string `json:"BgOrderPos"`
			SpeakingProf         string `json:"SpeakingProf"`
		} `json:"Languages"`
		Education struct {
			BackgroundElementID  string      `json:"BackgroundElementID"`
			SchoolCity           string      `json:"SchoolCity"`
			DegreeDate           string      `json:"DegreeDate"`
			LastModifiedDateTime string      `json:"LastModifiedDateTime"`
			SchoolState          string      `json:"SchoolState"`
			EndDate              string      `json:"EndDate"`
			SchoolCountry        string      `json:"SchoolCountry"`
			SchoolType           string      `json:"SchoolType"`
			SchoolPhone          string      `json:"SchoolPhone"`
			Major                string      `json:"Major"`
			PresentStudent       int         `json:"PresentStudent"`
			School               string      `json:"School"`
			BgOrderPos           string      `json:"BgOrderPos"`
			SchoolZip            string      `json:"SchoolZip"`
			Degree               string      `json:"Degree"`
			SchoolAddress        string      `json:"SchoolAddress"`
			CandidateID          string      `json:"CandidateID"`
			StartDate            string      `json:"StartDate"`
		} `json:"Education"`
		Certificates struct {
			BackgroundElementID  string `json:"BackgroundElementID"`
			LastModifiedDateTime string `json:"LastModifiedDateTime"`
			LicenseState         string `json:"LicenseState"`
			EndDate              string `json:"EndDate"`
			Description          string `json:"Description"`
			LicenseName          string `json:"LicenseName"`
			Institution          string `json:"Institution"`
			LicenseType          string `json:"LicenseType"`
			Name                 string `json:"Name"`
			BgOrderPos           string `json:"BgOrderPos"`
			LicenseCountry       string `json:"LicenseCountry"`
			LicenseNumber        string `json:"LicenseNumber"`
			CandidateID          string `json:"CandidateID"`
			StartDate            string `json:"StartDate"`
		} `json:"Certificates"`
		OutsideWorkExperience struct {
			BackgroundElementID  string `json:"BackgroundElementID"`
			EmployerAddress      string `json:"EmployerAddress"`
			LastModifiedDateTime string `json:"LastModifiedDateTime"`
			EndDate              string `json:"EndDate"`
			EmployerState        string `json:"EmployerState"`
			StartTitle           string `json:"StartTitle"`
			BgOrderPos           string `json:"BgOrderPos"`
			Employer             string `json:"Employer"`
			EmployerPhone        string `json:"EmployerPhone"`
			PresentEmployer      string `json:"PresentEmployer"`
			EmployerCountry      string `json:"EmployerCountry"`
			EmployerZip          string `json:"EmployerZip"`
			EmployerCity         string `json:"EmployerCity"`
			EmployerEmail        string `json:"EmployerEmail"`
			BusinessType         string `json:"BusinessType"`
			CandidateID          string `json:"CandidateID"`
			EmployerContact      string `json:"EmployerContact"`
			StartDate            string `json:"StartDate"`
		} `json:"OutsideWorkExperience"`
	} `json:"Candidate"`
	APISchema   string   `json:"api_schema"`
	Accepter    []string `json:"accepter"`
	CandidateID string   `json:"candidate_id"`
	Deleted     bool     `json:"deleted"`
}
